const PulseEngine = {
    sectors: {
        geopolitics: ["US-Iran Peace Proposal: Markets rally as Tehran evaluates formal exit strategy.", "Diplomatic Handshake: Omani Mediators confirm breakthrough in Multilateral Tensions.", "Geopolitical Pivot: Risk premiums subside across Asian markets following peace signals.", "Middle East Stability: Defense sectors shift focus to long-term regional infrastructure.", "Global Security: Neutrality protocols gain traction in Northern European corridors."],
        entertainment: ["Steven Spielberg’s 'Disclosure Day': Emily Blunt and Josh O'Connor lead high-fidelity cinematic debut.", "Streaming Pulse: New Netflix and Hulu releases for June 12 achieve record viewer engagement.", "World Cup Betting: Jake Paul places high-stakes wager on US victory in upcoming match.", "Music Intelligence: New album drops for June 12 redefine summer acoustic standards.", "Box Office Inflow: Summer Blockbusters see record ticket volume in Asian markets."],
        blockchain: ["SpaceX IPO Handshake: $75B Public Debut leverages on-chain treasury verification.", "Treasury Enforcement: Sanctions targeting terror-finance drive institutional shift to Regulated DeFi.", "Digital Asset Recovery: Global markets stabilize as 'Geopolitical Whiplash' eases.", "SEC Innovation: New framework for Tokenized Infrastructure Bonds finalized.", "Neural Ledger: $PRN Token achieves 100% stable deployment in institutional pilots."],
        biohacking: ["Longevity Breakthrough: NAD+ Precursors show record efficacy in cellular age-reversal.", "Neural Benchmarks: New CGMs achieve 99% accuracy in real-time metabolic diagnostics.", "Roche Obesity Trials: Results outpace industry targets for Q3 deployment.", "Metabolic Engineering: Personalized DNA-based nutrition enters Phase 3.", "Regenerative Vision: High-fidelity ocular implants receive secondary-tier clearance."],
        markets: ["SpaceX IPO: Historic $75B public debut triggers record tech sector inflows.", "Nasdaq Rally: Global indices gain momentum on US-Iran peace deal hopes.", "Commodity Shift: Gold stabilizes as safe-haven flows rotate into growth assets.", "Tech Infrastructure: High-fidelity server farms see 20% volume increase in Q2.", "Economic Independence: Logistics networks adapt to localized production corridors."],
        anime: [],
        stocks: ["Tech Sector Surge: AI-chipmakers lead S&P 500 to fresh June highs.", "IPO Market Rebirth: SpaceX debut signals return of institutional appetite.", "Industrial Sentiment: Sentiment remains Bullish following infrastructure bill updates.", "Dividend Growth: Top-tier equities announce record yields for Elite holders.", "Semiconductor Index: Supply-chain audits confirm strong capacity for H2 2026."],
        lifestyle: ["Resilient Habitat: Lord Norman Foster addresses Madrid CityLab.", "Smart Cities: AI Integration optimizes urban resource logistics in real-time.", "Minimalist Architecture: Focus shifts to subterranean sanctuary designs.", "Wellness Engineering: Bio-sensors become standard in high-end luxury smart-homes."],
        forex: ["Forex Stability: Major pairs stabilize at 1.33045 as risk sentiment improves.", "US Dollar Index: DXY holds steady as investors evaluate Middle East peace odds.", "JPY Pivot: Yen strengthens slightly against USD as carry-trades unwind.", "Euro-Zone: ECB inflation targets met, bolsters recovery sentiment.", "GBP Resilience: UK labor data confirms Sterling as top-tier growth pair."],
        realestate: ["Tokenized Equity: Real-estate investment pools see record Participation.", "Veteran Housing: New preservation strategies implemented for regional policy.", "Luxury Listings: Mumbai Supercar Launch triggers high-end property interest.", "Eco-Friendly Construction: Sustainable builds become the industry gold standard.", "Commercial Conversion: Post-office hubs adapted into high-fidelity AI-centers."]
    },
    ads: [
        { brand: "ORCINOS", text: "Apex Intelligence for the elite architect.", link: "https://orcinos.com/" },
        { brand: "GLOW PROTOCOL", text: "DNA-optimized skincare. Enter the future.", link: "https://orcinos.com/glowprotocol/" },
        { brand: "ATELIA GAMING", text: "The independent economy of play.", link: "https://orcinos.com/ateliagaming/" },
        { brand: "PEAK FIT", text: "Biohacking performance metrics. Join the elite.", link: "https://orcinos.com/peakfit/" },
        { brand: "COUTURE GALLERY", text: "High-end bags. Archival craftsmanship.", link: "https://orcinos.com/couturegallery/" }
    ],
    init() { this.updateDate(); this.fetchAnimeNews(); this.startTickers(); this.updateSectors(); this.updateAds(); this.injectMessenger(); },
    updateDate() { const el = document.getElementById('current-date'); if (el) { const now = new Date(); const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }; el.innerText = now.toLocaleDateString('en-US', options).toUpperCase() + ' · ELITE FREQUENCY 104.2'; } },
    async fetchAnimeNews() { try { const res = await fetch('https://api.jikan.moe/v4/seasons/now'); if (!res.ok) { console.error("Jikan API error:", res.status, res.statusText); this.sectors.anime = ["Trending: Tongari Boushi no Atelier leads Seasonal Viewership.", "Grand Blue Dreaming Season 3 confirmed.", "High-Fidelity Animation standard achieved."]; return; } const data = await res.json(); if (data && data.data) { this.sectors.anime = data.data.slice(0, 10).map(item => `Trending: ${item.title_english || item.title} (${item.status}) leads seasonal viewership.`); } } catch (err) { console.error("Failed to fetch anime news:", err); this.sectors.anime = ["Trending: Tongari Boushi no Atelier leads Seasonal Viewership.", "Grand Blue Dreaming Season 3 confirmed.", "High-Fidelity Animation standard achieved."]; } },
    startTickers() { const el = document.getElementById('live-ticker'); if (el) setInterval(() => { const prn = (4.0 + Math.random() * 0.5).toFixed(2); const eth = (3500 + Math.random() * 50).toFixed(0); el.innerHTML = `MARKET: $PRN +${prn}% · ETH $${eth} · Intelligence: <span style="color:#D0021B; font-weight:800;">LIVE</span>`; }, 3000); },
    updateSectors() { const keys = Object.keys(this.sectors); let idx = 0; setInterval(() => { const s = keys[idx % keys.length]; const el = document.getElementById(`news-${s}`); if (el && this.sectors[s].length > 0) { el.style.opacity = 0; setTimeout(() => { el.innerText = this.sectors[s][Math.floor(Math.random() * this.sectors[s].length)]; el.style.opacity = 1; }, 500); } idx++; }, 4000); },
    updateAds() { const ads = document.querySelectorAll('.ticker-item.brand'); ads.forEach((ad, i) => { setInterval(() => { const ra = this.ads[Math.floor(Math.random() * this.ads.length)]; const s = ad.querySelector('span'); const p = ad.querySelector('p'); if (s && p) { ad.style.opacity = 0; setTimeout(() => { s.innerText = ra.brand; p.innerText = ra.text; ad.style.opacity = 1; }, 500); } }, 10000 + (i * 2000)); }); },
    injectMessenger() { if (document.getElementById('orc-messenger')) return; const m = document.createElement('div'); m.id = 'orc-messenger'; m.style = "position:fixed;bottom:30px;right:30px;width:min(350px,90vw);height:500px;background:white;border:4px solid black;box-shadow:0 20px 50px rgba(0,0,0,0.3);z-index:5000;display:flex;flex-direction:column;font-family:'Inter',sans-serif;transition:transform 0.3s ease;"; m.innerHTML = `<div style="background:black;color:white;padding:15px;font-weight:800;font-size:0.75rem;letter-spacing:2px;display:flex;justify-content:space-between;align-items:center;cursor:pointer;" onclick="toggleMessenger()"><span>NEURAL DESK | ORCPULSE</span><span id="msg-toggle-icon">_</span></div><div id="chat-stream" style="flex:1;padding:20px;overflow-y:auto;font-size:0.85rem;line-height:1.4;color:#333;background:#fff;"><div><strong>SYSTEM:</strong> Neural handshake established. Sector parity confirmed.</div></div><div style="padding:15px;border-top:1px solid #eee;background:#fff;"><input type="text" placeholder="Type a command..." style="width:100%;border:2px solid #000;padding:10px;font-family:inherit;font-size:0.8rem;outline:none;"></div>`; document.body.appendChild(m); window.toggleMessenger = () => { const ms = document.getElementById('orc-messenger'); const ic = document.getElementById('msg-toggle-icon'); if (ms.style.transform === 'translateY(calc(100% - 45px))') { ms.style.transform = 'translateY(0)'; ic.innerText = '_'; } else { ms.style.transform = 'translateY(calc(100% - 45px))'; ic.innerText = '^'; } }; const st = document.getElementById('chat-stream'); setInterval(() => { const sk = Object.keys( PulseEngine.sectors ).filter(s => PulseEngine.sectors[s].length > 0); const s = sk[Math.floor(Math.random() * sk.length)]; const msg = document.createElement('div'); msg.style.marginBottom = '15px'; msg.style.opacity = 0; msg.style.transition = 'opacity 0.5s ease'; msg.innerHTML = '<strong>' + s.toUpperCase() + ':</strong> ' + PulseEngine.sectors[s][Math.floor(Math.random() * PulseEngine.sectors[s].length)]; st.appendChild(msg); setTimeout(() => msg.style.opacity = 1, 10); st.scrollTop = st.scrollHeight; if (st.children.length > 20) st.removeChild(st.firstChild); }, 8000); } };
document.addEventListener('DOMContentLoaded', () => PulseEngine.init());
