const PulseEngine = {
sectors: {
geopolitics: ["Omani Mediators Relay Tehran’s Formal Counteroffer to US.", "Strategic Initiative: Regional Channels Evaluate Multilateral Mediation.", "Elite Defense: AI-Driven Pulse Processing prioritized in Security Budget.", "Arctic Logistics: New Shipping Lanes Redefine Northern Trade Routes.", "Energy Security: Diplomatic Accord stabilizing Mediterranean Gas Exports."],
blockchain: ["SEC Finalizes Innovation Exemption for Tokenized Stocks.", "Ledger Efficiency: Major Exchange Finalizes Automated Proof-of-Reserve.", "Neural Ledger: $PRN Token Utility reaches 100% stable deployment.", "Smart Contracts: Layer 2 Solutions achieve sub-millisecond Finality.", "Digital Identity: Standardized DID Protocols adopted by major Financial Hubs."],
biohacking: ["Roche Obesity Drug outpaces Industry Targets in latest trials.", "Neural Benchmarks: New CGMs achieve 99% accuracy in real-time diagnostics.", "Regenerative Treatment: Scientific consensus emerging around neural-calibration.", "Longevity Science: NAD+ Precursors show record efficacy in cellular age-reversal.", "Metabolic Engineering: Personalized DNA-based nutrition enters Phase 3."],
markets: ["Nasdaq Rebound: Chipmakers Lead Recovery Post-Selloff.", "Institutional Inflow: Tech Infrastructure Bonds see Record Volume.", "Global Fragmentation: Trade Logistics adapt to Economic Independence shift.", "Commodity Surge: Rare Earth Elements stabilize following supply-chain audit.", "Bond Yields: Treasury yields consolidate as inflation expectations align."],
anime: [],
stocks: ["Dow Jones Futures: Industrial Sentiment remains Bullish.", "Tech Sector Resilience: S&P 500 maintains level despite volatility.", "Dividend Growth: Top-tier equities announce record yields.", "Small-Cap Rally: Infrastructure bill spurs growth in specialized manufacturing.", "Semiconductor Index: AI demand maintains upward pressure on valuation."],
lifestyle: ["Resilient Habitat: Lord Norman Foster addresses Madrid CityLab.", "Smart Cities: AI Integration optimizes urban resource logistics.", "Minimalist Architecture: Focus on sanctuary-based living spaces.", "Bespoke Living: High-end residential designs prioritize thermal efficiency.", "Wellness Tech: Integrated bio-sensors become standard in luxury smart-homes."],
forex: ["USD/JPY Stability: Central Banks maintain current policy stance.", "Euro-Zone Outlook: Inflation targets met, markets stabilize.", "GBP/USD Resilience: Strong labor data bolsters Sterling.", "Swiss Franc: Safe-haven flows consolidate amid European fiscal updates.", "AUD/USD Pivot: Commodity pricing bolsters Pacific currency pairs."],
realestate: ["Veteran housing policy needs a preservation strategy.", "Luxury Listings: High-end properties see increased international demand.", "Sustainable Development: Eco-friendly construction becomes industry standard.", "Commercial Pivot: Post-office hubs converted into high-fidelity AI-centers.", "Tokenized Assets: Real-estate equity pools see record participation."]
},
ads: [
{ brand: "ORCINOS", text: "Apex Intelligence for the elite architect.", link: "https://orcinos.com/" },
{ brand: "GLOW PROTOCOL", text: "DNA-optimized skincare. Enter the future.", link: "https://orcinos.com/glowprotocol/" },
{ brand: "ATELIA GAMING", text: "The independent economy of play.", link: "https://orcinos.com/ateliagaming/" },
{ brand: "PEAK FIT", text: "Biohacking performance metrics. Join the elite.", link: "https://orcinos.com/peakfit/" },
{ brand: "COUTURE GALLERY", text: "High-end bags. Archival craftsmanship.", link: "https://orcinos.com/couturegallery/" }
],
init() { this.updateDate(); this.fetchAnimeNews(); this.startTickers(); this.updateSectors(); this.updateAds(); this.injectMessenger(); },
updateDate() { const el = document.getElementById('current-date'); if (el) { const now = new Date(); const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }; el.innerText = now.toLocaleDateString('en-US', options).toUpperCase() + ' · ELITE FREQUENCY 104.2'; } },
async fetchAnimeNews() { try { const res = await fetch('https://api.jikan.moe/v4/seasons/now'); const data = await res.json(); if (data && data.data) { this.sectors.anime = data.data.slice(0, 8).map(item => `Trending: ${item.title_english || item.title} (${item.status}) leads seasonal viewership.`); } } catch (err) { this.sectors.anime = ["Trending: Tongari Boushi no Atelier leads Seasonal Viewership.", "Grand Blue Dreaming Season 3 confirmed.", "High-Fidelity Animation standard achieved."]; } },
startTickers() { const el = document.getElementById('live-ticker'); if (el) setInterval(() => { const prn = (4.0 + Math.random() * 0.5).toFixed(2); const eth = (3500 + Math.random() * 50).toFixed(0); el.innerHTML = `MARKET: $PRN +${prn}% · ETH $${eth} · Intelligence: <span style="color:#D0021B; font-weight:800;">LIVE</span>`; }, 3000); },
updateSectors() { const keys = Object.keys(this.sectors); let idx = 0; setInterval(() => { const s = keys[idx % keys.length]; const el = document.getElementById(`news-${s}`); if (el && this.sectors[s].length > 0) { el.style.opacity = 0; setTimeout(() => { el.innerText = this.sectors[s][Math.floor(Math.random() * this.sectors[s].length)]; el.style.opacity = 1; }, 500); } idx++; }, 4000); },
updateAds() { const ads = document.querySelectorAll('.ticker-item.brand'); ads.forEach((ad, i) => { setInterval(() => { const ra = this.ads[Math.floor(Math.random() * this.ads.length)]; const s = ad.querySelector('span'); const p = ad.querySelector('p'); if (s && p) { ad.style.opacity = 0; setTimeout(() => { s.innerText = ra.brand; p.innerText = ra.text; ad.style.opacity = 1; }, 500); } }, 10000 + (i * 2000)); }); },
injectMessenger() { if (document.getElementById('orc-messenger')) return; const m = document.createElement('div'); m.id = 'orc-messenger'; m.style = "position:fixed;bottom:30px;right:30px;width:min(350px,90vw);height:500px;background:white;border:4px solid black;box-shadow:0 20px 50px rgba(0,0,0,0.3);z-index:5000;display:flex;flex-direction:column;font-family:'Inter',sans-serif;transition:transform 0.3s ease;"; m.innerHTML = `<div style="background:black;color:white;padding:15px;font-weight:800;font-size:0.75rem;letter-spacing:2px;display:flex;justify-content:space-between;align-items:center;cursor:pointer;" onclick="toggleMessenger()"><span>NEURAL DESK | ORCPULSE</span><span id="msg-toggle-icon">_</span></div><div id="chat-stream" style="flex:1;padding:20px;overflow-y:auto;font-size:0.85rem;line-height:1.4;color:#333;background:#fff;"><div><strong>SYSTEM:</strong> Neural handshake established. Sector parity confirmed.</div></div><div style="padding:15px;border-top:1px solid #eee;background:#fff;"><input type="text" placeholder="Type a command..." style="width:100%;border:2px solid #000;padding:10px;font-family:inherit;font-size:0.8rem;outline:none;"></div>`; document.body.appendChild(m); window.toggleMessenger = () => { const ms = document.getElementById('orc-messenger'); const ic = document.getElementById('msg-toggle-icon'); if (ms.style.transform === 'translateY(calc(100% - 45px))') { ms.style.transform = 'translateY(0)'; ic.innerText = '_'; } else { ms.style.transform = 'translateY(calc(100% - 45px))'; ic.innerText = '^'; } }; const st = document.getElementById('chat-stream'); setInterval(() => { const sk = Object.keys( PulseEngine.sectors ).filter(s => PulseEngine.sectors[s].length > 0); const s = sk[Math.floor(Math.random() * sk.length)]; const msg = document.createElement('div'); msg.style.marginBottom = '15px'; msg.style.opacity = 0; msg.style.transition = 'opacity 0.5s ease'; msg.innerHTML = `<strong>${s.toUpperCase()}:</strong> ${PulseEngine.sectors[s][Math.floor(Math.random() * PulseEngine.sectors[s].length)]}`; st.appendChild(msg); setTimeout(() => msg.style.opacity = 1, 10); st.scrollTop = st.scrollHeight; if (st.children.length > 20) st.removeChild(st.firstChild); }, 8000); } };
document.addEventListener('DOMContentLoaded', () => PulseEngine.init());
